// David M Allen
// Error codes
// COP 3402 - Systems Software

#ifndef ERRORHANDLER_H
#define ERRORHANDLER_H

    #define BADCONSTASSIGNMENTSYMBOL 1
    #define CONSTASSIGNMENTMISSING 2
    #define MISSINGCONSTASSIGNMENTSYMBOL 3
    #define MISSINGIDENTIFIER 4
    #define MISSINGSEMICOLONORCOMMA 5
    #define BADSYMBOLAFTERPROCDECL 6
    #define MISSINGSTATEMENT 7
    #define BADSYMBOLAFTERSTMTINBLOCK 8
    #define MISSINGPERIOD 9
    #define MISSINGSEMICOLON 10
    #define UNDECLAREDIDENT 11
    #define INVALIDASSIGNMENT 12
    #define MISSINGOPERATOR 13
    #define MISSINGIDENTAFTERCALL 14
    #define INVALIDCALL 15
    #define MISSINGTHENAFTERIF 16
    #define MISSINGSEMICOLONORBRACKET 17
    #define MISSINGDO 18
    #define BADSYMBOLAFTERSTMT 19
    #define MISSINGRELATIONALOPERATOR 20
    #define BADUSEOFPROCIDENT 21
    #define MISSINGRIGHTPAREN 22
    #define INVALIDSTARTTOFACTOR 23
    #define INVALIDSTARTTOEXPRESSION 24
    #define TOOLARGENUMBER 25
    #define INVALIDINPUTARGUMENTS 26
    #define MISSINGINPUTARGUMENTS 27
    #define TOOMANYINPUTARGUMENTS 28
    #define NOTIMPLEMENTEDCALL 29
    #define NOTIMPLEMENTEDELSE 30
    #define NOTIMPLEMENTED 31

#endif // ERRORHANDLER_H
